name: Build and Deploy Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: |
          mkdir _pages 
          mv README.md _pages/index.md 
          rm -rf !'_pages'

      - name: Setup Hyde.yml
        run: |
          echo 'name: Speacher' >> hyde.yml
          echo 'load_app_styles_from_cdn: true' >> hyde.yml
          # Highlight.js
          echo "footer: '<div>Site proudly built with <a href=\"https://github.com/hydephp/hyde\">HydePHP</a> 🎩</div><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7.0/build/styles/atom-one-dark.min.css\"> <script src=\"https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7.0/build/highlight.min.js\"></script> <script>hljs.highlightAll();</script> <style>.prose :where(pre) { background-color: #282c34; } </style> <style>pre code.hljs { padding: 0; }</style>'" >> hyde.yml

      - uses: hydephp/action@v0.7.1
        with:
          deploy-to: "pages"
